mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
db:
  ##从库数量
  datasourceNum: 1
  ##单个从库中从表数量1
  tableNum: 2
  ##主表名List
  tableNames: user123,admin,category,coupon,deposit,favorite,feedback,footmark,forder,mall_activity,pic,product,product_comment,refund,safe_question,sorder,user_address,home,message
  ##主库名，从库名为主库名+0~datasource_num
  dataName: db
  ##分表键
  tableKey: id
  ##分表策略截取id长度，分库从0-key_length,分表从key_length-end
  keyLength: 4
  ##主库
  mainData: dbo
  ##默认库,当没有配置策略时使用
  defaultData: db0
  dbconfig:
    datasource1:
      ##定义名字时必须末尾从0开始的连续数字
      dataName: db0
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.106.89.153:3306/db0?useUnicode=true&characterEncoding=utf-8
      userName: root
      password: 123456
#    datasource2:
#      dataName: test1
#      driverClass: com.mysql.jdbc.Driver
#      url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=true
#      userName: root
#      password: 123456
